environment:
  CEPH_VERSION: 15.2.9
  KUBE_VERSION: 1.25.1
  DOCKER_VERSION: 20.10.18-3
  CRIO_MAJOR_VERSION: 1.25
  CRIO_VERSION: 1.25.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build an amd64 container image
          command: |
            curl -L -o ${PWD}/centos7-devel-kubic-libcontainers-stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
            curl -L -o ${PWD}/centos7-devel-kubic-libcontainers-stable-cri-o-${CRIO_MAJOR_VERSION}.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${CRIO_MAJOR_VERSION}/CentOS_7/devel:kubic:libcontainers:stable:cri-o:${CRIO_MAJOR_VERSION}.repo
            curl -L -o ${PWD}/centos8-devel-kubic-libcontainers-stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
            curl -L -o ${PWD}/centos8-devel-kubic-libcontainers-stable-cri-o-${CRIO_MAJOR_VERSION}.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/${CRIO_MAJOR_VERSION}/CentOS_8/devel:kubic:libcontainers:stable:cri-o:${CRIO_MAJOR_VERSION}.repo
            docker run -itd --name=podman3-centos7 --entrypoint=/bin/sh wise2c/podman3:centos7
            mkdir -p ${PWD}/rpms/crio && docker cp podman3-centos7:/centos7 ${PWD}/rpms/crio/
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo centos:7.5.1804 bash -c
            "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
             yum install -y https://download.ceph.com/rpm-${CEPH_VERSION}/el7/noarch/ceph-release-1-1.el7.noarch.rpm &&
             yum install -y yum-utils &&
             yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo &&
             mkdir -p /rpms/k8s/centos7 &&
             yum remove -y python-chardet chrony &&
             yum -y install --downloadonly --downloaddir=/rpms/k8s/centos7 docker-ce-${DOCKER_VERSION}.el7 docker-ce-cli-${DOCKER_VERSION}.el7 docker-python docker-compose python-chardet python-requests &&
             yum -y install --downloadonly --downloaddir=/rpms/k8s/centos7 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz &&
             yum -y install --downloadonly --downloaddir=/rpms/k8s/centos7 ceph-deploy ceph ceph-radosgw radosgw-agent rbd-nbd rbd-mirror open-vm-tools nfs-utils &&
             yum -y install --downloadonly --downloaddir=/rpms/k8s/centos7 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} kubernetes-cni"
