jobs:
  build-branches-amd64:
    environment:
      KUBE_VERSION: '1.29.1'
      DOCKER_VERSION: '24.0.6-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.1'
    machine: true
    steps:
      - checkout
      - run:
          name: Build an amd64 container image
          command: |
            sudo mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -v ${PWD}/CentOS8.yepo:/etc/yum.repos.d/CentOS8.repo alanpeng/kylinos:v10-sp2 bash -c \
              "yum install -y createrepo && \
               mkdir -p /rpms/k8s/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               mkdir -p /rpms/crio/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 cri-o && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 podman"
            docker run -itd --name=kylin-yumrepo --entrypoint=/bin/sh alanpeng/kylin-breeze-yumrepo:v10-sp2
            docker cp kylin-yumrepo:/root/yum-install-cache.tar.gz ${PWD}/
            docker stop kylin-yumrepo && docker rm kylin-yumrepo
            tar zxf ${PWD}/yum-install-cache.tar.gz
            sudo mkdir -p ${PWD}/rpms/docker/centos8
            sudo cp ${PWD}/yum-install-cache/*.rpm ${PWD}/rpms/crio/centos8/
            sudo rm -rf ${PWD}/yum-install-cache
            docker run -t --rm -v ${PWD}/rpms:/rpms alanpeng/kylinos:v10-sp2 bash -c \
              "yum install -y createrepo && \
               yum clean all && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:amd64-$CIRCLE_BRANCH .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:amd64-$CIRCLE_BRANCH

  build-tags-amd64:
    environment:
      KUBE_VERSION: '1.29.1'
      DOCKER_VERSION: '24.0.6-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.1'
    machine: true
    steps:
      - checkout
      - run:
          name: Build an amd64 container image
          command: |
            sudo mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo alanpeng/kylinos:v10-sp2 bash -c \
              "yum install -y createrepo && \
               mkdir -p /rpms/k8s/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               mkdir -p /rpms/crio/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 cri-o http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/podman-4.9.2-1.module_el8+899+3d7192e3.x86_64.rpm"
            docker run -itd --name=kylin-yumrepo --entrypoint=/bin/sh alanpeng/kylin-breeze-yumrepo:v10-sp2
            docker cp kylin-yumrepo:/root/yum-install-cache.tar.gz ${PWD}/
            docker stop kylin-yumrepo && docker rm kylin-yumrepo
            tar zxf ${PWD}/yum-install-cache.tar.gz
            sudo mkdir -p ${PWD}/rpms/docker/centos8
            sudo cp ${PWD}/yum-install-cache/*.rpm ${PWD}/rpms/crio/centos8/
            sudo rm -rf ${PWD}/yum-install-cache
            docker run -t --rm -v ${PWD}/rpms:/rpms alanpeng/kylinos:v10-sp2 bash -c \
              "yum install -y createrepo && \
               yum clean all && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:amd64-$CIRCLE_TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:amd64-$CIRCLE_TAG

  build-branches-aarch64:
    environment:
      KUBE_VERSION: '1.29.1'
      DOCKER_VERSION: '24.0.6-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.1'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build an aarch64 container image
          command: |
            docker run -itd --name kylinos-v10-sp3 --entrypoint=/bin/bash alanpeng/kylinos:v10-sp3
            docker cp kylinos-v10-sp3:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem ${PWD}/
            docker stop kylinos-v10-sp3 && docker rm kylinos-v10-sp3
            mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo \
                                                    -v ${PWD}/tls-ca-bundle.pem:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem alanpeng/kylinos:v10-sp2-aarch64 bash -c \
              "mkdir -p /rpms/k8s/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               mkdir -p /rpms/crio/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/crio/centos8 cri-o http://mirror.centos.org/centos/8-stream/AppStream/aarch64/os/Packages/podman-4.9.2-1.module_el8+899+3d7192e3.aarch64.rpm"
            docker run -itd --name=kylin-yumrepo --entrypoint=/bin/sh alanpeng/kylin-breeze-yumrepo:v10-sp2-aarch64
            docker cp kylin-yumrepo:/root/yum-install-cache.tar.gz ${PWD}/
            docker stop kylin-yumrepo && docker rm kylin-yumrepo
            tar zxf ${PWD}/yum-install-cache.tar.gz
            sudo cp ${PWD}/yum-install-cache/*.rpm ${PWD}/rpms/crio/centos8/
            sudo rm -rf ${PWD}/yum-install-cache
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/tls-ca-bundle.pem:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem alanpeng/kylinos:v10-sp2-aarch64 bash -c \
              "yum install -y createrepo && \
               yum clean all && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:aarch64-$CIRCLE_BRANCH .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:aarch64-$CIRCLE_BRANCH

  build-tags-aarch64:
    environment:
      KUBE_VERSION: '1.29.1'
      DOCKER_VERSION: '24.0.6-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.1'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build an aarch64 container image
          command: |
            docker run -itd --name kylinos-v10-sp3 --entrypoint=/bin/bash alanpeng/kylinos:v10-sp3
            docker cp kylinos-v10-sp3:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem ${PWD}/
            docker stop kylinos-v10-sp3 && docker rm kylinos-v10-sp3
            mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo \
                                                    -v ${PWD}/tls-ca-bundle.pem:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem alanpeng/kylinos:v10-sp2-aarch64 bash -c \
              "mkdir -p /rpms/k8s/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               mkdir -p /rpms/crio/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/crio/centos8 cri-o http://mirror.centos.org/centos/8-stream/AppStream/aarch64/os/Packages/podman-4.9.2-1.module_el8+899+3d7192e3.aarch64.rpm"
            docker run -itd --name=kylin-yumrepo --entrypoint=/bin/sh alanpeng/kylin-breeze-yumrepo:v10-sp2-aarch64
            docker cp kylin-yumrepo:/root/yum-install-cache.tar.gz ${PWD}/
            docker stop kylin-yumrepo && docker rm kylin-yumrepo
            tar zxf ${PWD}/yum-install-cache.tar.gz
            sudo cp ${PWD}/yum-install-cache/*.rpm ${PWD}/rpms/crio/centos8/
            sudo rm -rf ${PWD}/yum-install-cache
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/tls-ca-bundle.pem:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem alanpeng/kylinos:v10-sp2-aarch64 bash -c \
              "yum install -y createrepo && \
               yum clean all && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:aarch64-$CIRCLE_TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:aarch64-$CIRCLE_TAG

  build-branches-multi-arch:
    machine: true
    steps:
      - run:
          name: Build a multi-arch container image
          command: |
            docker manifest create wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:amd64-$CIRCLE_BRANCH wise2c/yum-repo:aarch64-$CIRCLE_BRANCH
            docker manifest annotate wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:amd64-$CIRCLE_BRANCH --os linux --arch amd64
            docker manifest annotate wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:aarch64-$CIRCLE_BRANCH --os linux --arch arm64
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker manifest push wise2c/yum-repo:$CIRCLE_BRANCH

  build-tags-multi-arch:
    machine: true
    steps:
      - run:
          name: Build a multi-arch container image
          command: |
            docker manifest create wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:amd64-$CIRCLE_TAG wise2c/yum-repo:aarch64-$CIRCLE_TAG
            docker manifest annotate wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:amd64-$CIRCLE_TAG --os linux --arch amd64
            docker manifest annotate wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:aarch64-$CIRCLE_TAG --os linux --arch arm64
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker manifest push wise2c/yum-repo:$CIRCLE_TAG

workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches-amd64
      - build-branches-aarch64
      - build-branches-multi-arch:
          requires:
            - build-branches-amd64
            - build-branches-aarch64
  build-for-tags:
    jobs:
      - build-tags-amd64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tags-aarch64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tags-multi-arch:
          requires:
            - build-tags-amd64
            - build-tags-aarch64
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
