jobs:
  build-branches-amd64:
    environment:
      KUBE_VERSION: '1.29.4'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.3'
    machine: true
    steps:
      - checkout
      - run:
          name: Build an amd64 container image
          command: |
            sudo mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/root/kubernetes.repo -v ${PWD}/cri-o.repo:/root/cri-o.repo \
                                                    -v ${PWD}/CentOS8.repo:/root/CentOS8.repo -v ${PWD}/docker-ce.repo:/root/docker-ce.repo openeuler/openeuler:22.03-lts-sp3 bash -c \
              "yum remove -y tar && \
               mkdir /root/default-repo && cp /etc/yum.repos.d/*.repo /root/default-repo/ && \
               yum install -y createrepo && \
               mkdir -p /rpms/base/centos8 && \
               mkdir -p /rpms/k8s/centos8 && \
               mkdir -p /rpms/crio/centos8 && \
               mkdir -p /rpms/docker/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/base/centos8 tar libselinux-python3 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz nfs-utils && \
               cp /root/kubernetes.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/cri-o.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/crio/centos8 cri-o podman && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/CentOS8.repo /root/docker-ce.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/docker/centos8 docker-ce-${DOCKER_VERSION}.el8 docker-ce-cli-${DOCKER_VERSION}.el8 && \
               createrepo /rpms/base/centos8 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:amd64-$CIRCLE_BRANCH .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:amd64-$CIRCLE_BRANCH

  build-tags-amd64:
    environment:
      KUBE_VERSION: '1.29.4'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.3'
    machine: true
    steps:
      - checkout
      - run:
          name: Build an amd64 container image
          command: |
            sudo mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/root/kubernetes.repo -v ${PWD}/cri-o.repo:/root/cri-o.repo \
                                                    -v ${PWD}/CentOS8.repo:/root/CentOS8.repo -v ${PWD}/docker-ce.repo:/root/docker-ce.repo openeuler/openeuler:22.03-lts-sp3 bash -c \
              "yum remove -y tar && \
               mkdir /root/default-repo && cp /etc/yum.repos.d/*.repo /root/default-repo/ && \
               yum install -y createrepo && \
               mkdir -p /rpms/base/centos8 && \
               mkdir -p /rpms/k8s/centos8 && \
               mkdir -p /rpms/crio/centos8 && \
               mkdir -p /rpms/docker/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/base/centos8 tar libselinux-python3 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz nfs-utils && \
               cp /root/kubernetes.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/cri-o.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/crio/centos8 cri-o podman && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/CentOS8.repo /root/docker-ce.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/docker/centos8 docker-ce-${DOCKER_VERSION}.el8 docker-ce-cli-${DOCKER_VERSION}.el8 && \
               createrepo /rpms/base/centos8 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:amd64-$CIRCLE_TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:amd64-$CIRCLE_TAG

  build-branches-aarch64:
    environment:
      KUBE_VERSION: '1.29.4'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.3'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build an aarch64 container image
          command: |
            sudo mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/root/kubernetes.repo -v ${PWD}/cri-o.repo:/root/cri-o.repo \
                                                    -v ${PWD}/CentOS8.repo:/root/CentOS8.repo -v ${PWD}/docker-ce.repo:/root/docker-ce.repo openeuler/openeuler:22.03-lts-sp3 bash -c \
              "yum remove -y tar && \
               mkdir /root/default-repo && cp /etc/yum.repos.d/*.repo /root/default-repo/ && \
               yum install -y createrepo && \
               mkdir -p /rpms/base/centos8 && \
               mkdir -p /rpms/k8s/centos8 && \
               mkdir -p /rpms/crio/centos8 && \
               mkdir -p /rpms/docker/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/base/centos8 tar libselinux-python3 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz nfs-utils && \
               cp /root/kubernetes.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/cri-o.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/crio/centos8 cri-o podman && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/CentOS8.repo /root/docker-ce.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/docker/centos8 docker-ce-${DOCKER_VERSION}.el8 docker-ce-cli-${DOCKER_VERSION}.el8 && \
               createrepo /rpms/base/centos8 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:aarch64-$CIRCLE_BRANCH .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:aarch64-$CIRCLE_BRANCH

  build-tags-aarch64:
    environment:
      KUBE_VERSION: '1.29.4'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.29'
      CRIO_VERSION: '1.29.3'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build an aarch64 container image
          command: |
            sudo mkdir ${PWD}/rpms
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/kubernetes.repo:/root/kubernetes.repo -v ${PWD}/cri-o.repo:/root/cri-o.repo \
                                                    -v ${PWD}/CentOS8.repo:/root/CentOS8.repo -v ${PWD}/docker-ce.repo:/root/docker-ce.repo openeuler/openeuler:22.03-lts-sp3 bash -c \
              "yum remove -y tar && \
               mkdir /root/default-repo && cp /etc/yum.repos.d/*.repo /root/default-repo/ && \
               yum install -y createrepo && \
               mkdir -p /rpms/base/centos8 && \
               mkdir -p /rpms/k8s/centos8 && \
               mkdir -p /rpms/crio/centos8 && \
               mkdir -p /rpms/docker/centos8 && \
               yum -y install --downloadonly --downloaddir=/rpms/base/centos8 tar libselinux-python3 chrony audit rsync jq git tcpdump nc bind-utils net-tools ipvsadm graphviz nfs-utils && \
               cp /root/kubernetes.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/k8s/centos8 kubectl-${KUBE_VERSION} kubelet-${KUBE_VERSION} kubeadm-${KUBE_VERSION} && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/cri-o.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/crio/centos8 cri-o podman && \
               rm -f /etc/yum.repos.d/*.repo && cp /root/CentOS8.repo /root/docker-ce.repo /root/default-repo/*.repo /etc/yum.repos.d/ && \
               yum -y install --downloadonly --downloaddir=/rpms/docker/centos8 docker-ce-${DOCKER_VERSION}.el8 docker-ce-cli-${DOCKER_VERSION}.el8 && \
               createrepo /rpms/base/centos8 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/crio/centos8 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:aarch64-$CIRCLE_TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:aarch64-$CIRCLE_TAG

  build-branches-multi-arch:
    machine: true
    steps:
      - run:
          name: Build a multi-arch container image
          command: |
            docker manifest create wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:amd64-$CIRCLE_BRANCH wise2c/yum-repo:aarch64-$CIRCLE_BRANCH
            docker manifest annotate wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:amd64-$CIRCLE_BRANCH --os linux --arch amd64
            docker manifest annotate wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:aarch64-$CIRCLE_BRANCH --os linux --arch arm64
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker manifest push wise2c/yum-repo:$CIRCLE_BRANCH

  build-tags-multi-arch:
    machine: true
    steps:
      - run:
          name: Build a multi-arch container image
          command: |
            docker manifest create wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:amd64-$CIRCLE_TAG wise2c/yum-repo:aarch64-$CIRCLE_TAG
            docker manifest annotate wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:amd64-$CIRCLE_TAG --os linux --arch amd64
            docker manifest annotate wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:aarch64-$CIRCLE_TAG --os linux --arch arm64
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker manifest push wise2c/yum-repo:$CIRCLE_TAG

workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches-amd64
      - build-branches-aarch64
      - build-branches-multi-arch:
          requires:
            - build-branches-amd64
            - build-branches-aarch64
  build-for-tags:
    jobs:
      - build-tags-amd64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tags-aarch64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tags-multi-arch:
          requires:
            - build-tags-amd64
            - build-tags-aarch64
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
