jobs:
  build-branches-amd64:
    environment:
      CEPH_VERSION: '18.2.1'
      KUBE_VERSION: '1.28.6'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.28'
      CRIO_VERSION: '1.28.3'
    machine: true
    steps:
      - checkout
      - run:
          name: Build an amd64 container image
          command: |
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos9.sh:/root/fetch-k8s-rpms-centos9.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:9.3 bash -c "/root/fetch-k8s-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos9.sh:/root/fetch-ceph-rpms-centos9.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:9.3 bash -c "/root/fetch-ceph-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos9.sh:/root/fetch-docker-rpms-centos9.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:9.3 bash -c "/root/fetch-docker-rpms-centos9.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos8.sh:/root/fetch-k8s-rpms-centos8.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:8.9 bash -c "/root/fetch-k8s-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos8.sh:/root/fetch-ceph-rpms-centos8.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:8.9 bash -c "/root/fetch-ceph-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos8.sh:/root/fetch-docker-rpms-centos8.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:8.9 bash -c "/root/fetch-docker-rpms-centos8.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms rockylinux:8.9 bash -c \
              "yum install -y createrepo && \
               createrepo /rpms/k8s/centos9 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/ceph/centos9 && \
               createrepo /rpms/ceph/centos8 && \
               createrepo /rpms/docker/centos9 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:amd64-$CIRCLE_BRANCH .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:amd64-$CIRCLE_BRANCH

  build-tags-amd64:
    environment:
      CEPH_VERSION: '18.2.1'
      KUBE_VERSION: '1.28.6'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.28'
      CRIO_VERSION: '1.28.3'
    machine: true
    steps:
      - checkout
      - run:
          name: Build an amd64 container image
          command: |
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos9.sh:/root/fetch-k8s-rpms-centos9.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:9.3 bash -c "/root/fetch-k8s-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos9.sh:/root/fetch-ceph-rpms-centos9.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:9.3 bash -c "/root/fetch-ceph-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos9.sh:/root/fetch-docker-rpms-centos9.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:9.3 bash -c "/root/fetch-docker-rpms-centos9.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos8.sh:/root/fetch-k8s-rpms-centos8.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:8.9 bash -c "/root/fetch-k8s-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos8.sh:/root/fetch-ceph-rpms-centos8.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:8.9 bash -c "/root/fetch-ceph-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos8.sh:/root/fetch-docker-rpms-centos8.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:8.9 bash -c "/root/fetch-docker-rpms-centos8.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms rockylinux:8.9 bash -c \
              "yum install -y createrepo && \
               createrepo /rpms/k8s/centos9 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/ceph/centos9 && \
               createrepo /rpms/ceph/centos8 && \
               createrepo /rpms/docker/centos9 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:amd64-$CIRCLE_TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:amd64-$CIRCLE_TAG

  build-branches-aarch64:
    environment:
      CEPH_VERSION: '18.2.1'
      KUBE_VERSION: '1.28.6'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.28'
      CRIO_VERSION: '1.28.3'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build an aarch64 container image
          command: |
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos9.sh:/root/fetch-k8s-rpms-centos9.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:9.3 bash -c "/root/fetch-k8s-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos9.sh:/root/fetch-ceph-rpms-centos9.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:9.3 bash -c "/root/fetch-ceph-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos9.sh:/root/fetch-docker-rpms-centos9.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:9.3 bash -c "/root/fetch-docker-rpms-centos9.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos8.sh:/root/fetch-k8s-rpms-centos8.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:8.9 bash -c "/root/fetch-k8s-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos8.sh:/root/fetch-ceph-rpms-centos8.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:8.9 bash -c "/root/fetch-ceph-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos8.sh:/root/fetch-docker-rpms-centos8.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:8.9 bash -c "/root/fetch-docker-rpms-centos8.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms rockylinux:8.9 bash -c \
              "yum install -y createrepo && \
               createrepo /rpms/k8s/centos9 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/ceph/centos9 && \
               createrepo /rpms/ceph/centos8 && \
               createrepo /rpms/docker/centos9 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:aarch64-$CIRCLE_BRANCH .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:aarch64-$CIRCLE_BRANCH

  build-tags-aarch64:
    environment:
      CEPH_VERSION: '18.2.1'
      KUBE_VERSION: '1.28.6'
      DOCKER_VERSION: '25.0.3-1'
      CRIO_MAJOR_VERSION: '1.28'
      CRIO_VERSION: '1.28.3'
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build an aarch64 container image
          command: |
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos9.sh:/root/fetch-k8s-rpms-centos9.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:9.3 bash -c "/root/fetch-k8s-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos9.sh:/root/fetch-ceph-rpms-centos9.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:9.3 bash -c "/root/fetch-ceph-rpms-centos9.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos9.sh:/root/fetch-docker-rpms-centos9.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:9.3 bash -c "/root/fetch-docker-rpms-centos9.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-k8s-rpms-centos8.sh:/root/fetch-k8s-rpms-centos8.sh -v ${PWD}/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo -v ${PWD}/cri-o.repo:/etc/yum.repos.d/cri-o.repo -e BASH_KUBE_VERSION=${KUBE_VERSION} rockylinux:8.9 bash -c "/root/fetch-k8s-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-ceph-rpms-centos8.sh:/root/fetch-ceph-rpms-centos8.sh -e BASH_CEPH_VERSION=${CEPH_VERSION} rockylinux:8.9 bash -c "/root/fetch-ceph-rpms-centos8.sh"
            docker run -t --rm -v ${PWD}/rpms:/rpms -v ${PWD}/dnf.conf:/etc/yum.repos.d/dnf.conf -v ${PWD}/fetch-docker-rpms-centos8.sh:/root/fetch-docker-rpms-centos8.sh -e BASH_DOCKER_VERSION=${DOCKER_VERSION} rockylinux:8.9 bash -c "/root/fetch-docker-rpms-centos8.sh"

            docker run -t --rm -v ${PWD}/rpms:/rpms rockylinux:8.9 bash -c \
              "yum install -y createrepo && \
               createrepo /rpms/k8s/centos9 && \
               createrepo /rpms/k8s/centos8 && \
               createrepo /rpms/ceph/centos9 && \
               createrepo /rpms/ceph/centos8 && \
               createrepo /rpms/docker/centos9 && \
               createrepo /rpms/docker/centos8"
            sudo chmod -R 755 ${PWD}/rpms
            docker build -t wise2c/yum-repo:aarch64-$CIRCLE_TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push wise2c/yum-repo:aarch64-$CIRCLE_TAG

  build-branches-multi-arch:
    machine: true
    steps:
      - run:
          name: Build a multi-arch container image
          command: |
            docker manifest create wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:amd64-$CIRCLE_BRANCH wise2c/yum-repo:aarch64-$CIRCLE_BRANCH
            docker manifest annotate wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:amd64-$CIRCLE_BRANCH --os linux --arch amd64
            docker manifest annotate wise2c/yum-repo:$CIRCLE_BRANCH wise2c/yum-repo:aarch64-$CIRCLE_BRANCH --os linux --arch arm64
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker manifest push wise2c/yum-repo:$CIRCLE_BRANCH

  build-tags-multi-arch:
    machine: true
    steps:
      - run:
          name: Build a multi-arch container image
          command: |
            docker manifest create wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:amd64-$CIRCLE_TAG wise2c/yum-repo:aarch64-$CIRCLE_TAG
            docker manifest annotate wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:amd64-$CIRCLE_TAG --os linux --arch amd64
            docker manifest annotate wise2c/yum-repo:$CIRCLE_TAG wise2c/yum-repo:aarch64-$CIRCLE_TAG --os linux --arch arm64
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker manifest push wise2c/yum-repo:$CIRCLE_TAG

workflows:
  version: 2
  build-for-branches:
    jobs:
      - build-branches-amd64
      - build-branches-aarch64
      - build-branches-multi-arch:
          requires:
            - build-branches-amd64
            - build-branches-aarch64
  build-for-tags:
    jobs:
      - build-tags-amd64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tags-aarch64:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-tags-multi-arch:
          requires:
            - build-tags-amd64
            - build-tags-aarch64
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
